# Modified version of epics-base CI scripts
# (see: https://github.com/epics-base/ci-scripts)
name: ads-ioc

# Trigger on pushes and PRs to any branch
on:
  push:
    paths-ignore:
      - 'documentation/*'
      - '**/*.html'
      - '**/*.md'
  pull_request:

env:
  SETUP_PATH: .ci-local:.ci

jobs:
  build-linux:
    name: "test build"
    runs-on: ubuntu-20.04
    #${{ matrix.os }}
    # Set environment variables from matrix parameters
    env:
      CMP: gcc
      BCFG: default
      # Required for our stuff:
      EPICS_HOST_ARCH: rhel7-x86_64
      # BASE: "3.15"
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install CI requirements
      run: python -m pip install git+https://github.com/klauer/whatrecord@enh_tweak_makefiles
    - name: Install module requirements
      run: |
        sudo apt-get -y update
        sudo apt-get -y install re2c
    - name: Configure cache for base and required modules
      id: cache-primes
      uses: actions/cache@v3
      with:
        path: ./cache
        key: ${{ runner.os }}
        # TODO -${{ hashFiles('**/files') }}
    - name: Download and build dependencies
      run: python prepare.py prepare ads-ioc
    - name: Check the cache directory
      run: ls -la ./cache
    - name: Build the IOC
      run: python prepare.py build ads-ioc
